version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fogu64
      MYSQL_DATABASE: sensors
      MYSQL_USER: nikos
      MYSQL_PASSWORD: fogu64
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
  py-scripts:
    stdin_open: true
    build: ./py-scripts
